name: bsync_app1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluentui_icons: ^1.0.0
  iconify_flutter: ^0.0.5

  curved_navigation_bar: ^1.0.3

  gap: ^3.0.1
  intl: ^0.17.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Variable.ttf

    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf

    - family: General-Sans
      fonts:
        - asset: fonts/GeneralSans-Regular.ttf
